# -*- coding: utf-8 -*-
"""
Extend the MKN-10 lookup for the new specialties.

Collects all 3-char diagnosis codes from gastro/chir/endo diagnosis_data.json,
finds those missing from src/mkn10_cs.js, fetches their Czech names from the
mkn10.uzis.cz search API and takes English names from the WHO ICD-10
classification (simple_icd_10).

The site is a Vue SPA, so scraping HTML yields nothing usable – the JSON API
below (discovered in the app bundle) is the working source:
    https://mkn10.uzis.cz/api/private/search?term=<CODE>
returning {"response": {"docs": [{"code": "...", "title": "..."}]}}

Outputs:
  src/mkn10_cs_ext.js  – Czech names for extra codes
  src/mkn10_en_ext.js  – English names for extra codes
"""
import io, json, re, sys, time, urllib.parse, urllib.request
from pathlib import Path

import simple_icd_10 as icd

sys.stdout.reconfigure(encoding="utf-8")
ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / "data_prep" / "mkn10_cache.json"
API = "https://mkn10.uzis.cz/api/private/search?term={}"

# 1) collect codes used by any specialty
codes = set()
for spec in ("gastro", "chir", "endo"):
    p = ROOT / "public" / "data" / spec / "diagnosis_data.json"
    if not p.exists():
        continue
    for diaglist in json.loads(p.read_text(encoding="utf-8")).values():
        for item in diaglist:
            c = (item.get("diag") or "").strip()
            if len(c) >= 2:
                codes.add(c[:3])

cs_src = (ROOT / "src" / "mkn10_cs.js").read_text(encoding="utf-8")
have = set(re.findall(r'^\s+([A-Z]\d{2}): "', cs_src, re.M))
missing = sorted(codes - have)
print(f"total codes {len(codes)}, covered {len(have & codes)}, missing {len(missing)}")

# 2) cache – drop values poisoned by the old HTML scraper
cache = json.loads(CACHE.read_text(encoding="utf-8")) if CACHE.exists() else {}
bad = [k for k, v in cache.items() if not v or v == k or v.strip() in ("Prohlížeč", "MKN-10")]
for k in bad:
    del cache[k]
if bad:
    print(f"dropped {len(bad)} bad cache entries")

def fetch_name(code):
    url = API.format(urllib.parse.quote(code))
    req = urllib.request.Request(url, headers={
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        "Accept": "application/json",
    })
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        for doc in data.get("response", {}).get("docs", []):
            if (doc.get("code") or "").upper() == code.upper():
                title = (doc.get("title") or "").strip()
                if title:
                    return title
    except Exception:
        pass
    return None

to_fetch = [c for c in missing if c not in cache]
print(f"fetching {len(to_fetch)} Czech names from the MKN-10 API…", flush=True)
ok = 0
for i, code in enumerate(to_fetch):
    name = fetch_name(code)
    if name:
        cache[code] = name
        ok += 1
    if (i + 1) % 100 == 0:
        print(f"  {i+1}/{len(to_fetch)}  (resolved {ok})", flush=True)
        CACHE.write_text(json.dumps(cache, ensure_ascii=False), encoding="utf-8")
    time.sleep(0.12)
CACHE.write_text(json.dumps(cache, ensure_ascii=False), encoding="utf-8")
print(f"Czech names resolved: {ok}/{len(to_fetch)}")

cs_ext = {c: cache[c] for c in missing if c in cache}

# 3) English names from WHO ICD-10
en_ext = {}
for c in missing:
    try:
        en_ext[c] = icd.get_description(c)
    except Exception:
        pass
print(f"English names resolved: {len(en_ext)}/{len(missing)}")

# 4) write generated modules
def write_module(path, var, mapping, comment):
    lines = [f"// {comment}",
             "// GENERATED by data_prep/fetch_mkn10_ext.py – do not edit by hand.",
             f"const {var} = {{"]
    for code in sorted(mapping):
        lines.append(f'  {code}: "{mapping[code].replace(chr(34), chr(92) + chr(34))}",')
    lines += ["};", "", f"export default {var};", ""]
    io.open(path, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print(f"wrote {path.name} ({len(mapping)} codes)")

write_module(ROOT / "src" / "mkn10_cs_ext.js", "MKN10_CS_EXT", cs_ext,
             "Czech MKN-10 names for codes outside the hand-curated gastro set (source: mkn10.uzis.cz API).")
write_module(ROOT / "src" / "mkn10_en_ext.js", "MKN10_EN_EXT", en_ext,
             "English ICD-10 (WHO) names for codes outside the hand-curated gastro set.")
print("DONE")
