/**
 * English ICD-10 (WHO) diagnosis code -> name lookup.
 * Generated from the WHO ICD-10 classification (simple_icd_10 package)
 * for the same code set as mkn10_cs.js. Fallback: Czech name.
 */
const MKN10_EN = {
  A00: "Cholera",
  A01: "Typhoid and paratyphoid fevers",
  A02: "Other salmonella infections",
  A03: "Shigellosis",
  A04: "Other bacterial intestinal infections",
  A05: "Other bacterial foodborne intoxications, not elsewhere classified",
  A06: "Amoebiasis",
  A07: "Other protozoal intestinal diseases",
  A08: "Viral and other specified intestinal infections",
  A09: "Other gastroenteritis and colitis of infectious and unspecified origin",
  A15: "Respiratory tuberculosis, bacteriologically and histologically confirmed",
  A16: "Respiratory tuberculosis, not confirmed bacteriologically or histologically",
  A17: "Tuberculosis of nervous system",
  A18: "Tuberculosis of other organs",
  A19: "Miliary tuberculosis",
  A40: "Streptococcal sepsis",
  A41: "Other sepsis",
  A49: "Bacterial infection of unspecified site",
  B15: "Acute hepatitis A",
  B16: "Acute hepatitis B",
  B17: "Other acute viral hepatitis",
  B18: "Chronic viral hepatitis",
  B19: "Unspecified viral hepatitis",
  B20: "Human immunodeficiency virus [HIV] disease resulting in infectious and parasitic diseases",
  B94: "Sequelae of other and unspecified infectious and parasitic diseases",
  C00: "Malignant neoplasm of lip",
  C01: "Malignant neoplasm of base of tongue",
  C02: "Malignant neoplasm of other and unspecified parts of tongue",
  C03: "Malignant neoplasm of gum",
  C04: "Malignant neoplasm of floor of mouth",
  C05: "Malignant neoplasm of palate",
  C06: "Malignant neoplasm of other and unspecified parts of mouth",
  C07: "Malignant neoplasm of parotid gland",
  C08: "Malignant neoplasm of other and unspecified major salivary glands",
  C09: "Malignant neoplasm of tonsil",
  C10: "Malignant neoplasm of oropharynx",
  C11: "Malignant neoplasm of nasopharynx",
  C12: "Malignant neoplasm of piriform sinus",
  C13: "Malignant neoplasm of hypopharynx",
  C14: "Malignant neoplasm of other and ill-defined sites in the lip, oral cavity and pharynx",
  C15: "Malignant neoplasm of oesophagus",
  C16: "Malignant neoplasm of stomach",
  C17: "Malignant neoplasm of small intestine",
  C18: "Malignant neoplasm of colon",
  C19: "Malignant neoplasm of rectosigmoid junction",
  C20: "Malignant neoplasm of rectum",
  C21: "Malignant neoplasm of anus and anal canal",
  C22: "Malignant neoplasm of liver and intrahepatic bile ducts",
  C23: "Malignant neoplasm of gallbladder",
  C24: "Malignant neoplasm of other and unspecified parts of biliary tract",
  C25: "Malignant neoplasm of pancreas",
  C26: "Malignant neoplasm of other and ill-defined digestive organs",
  C34: "Malignant neoplasm of bronchus and lung",
  C50: "Malignant neoplasm of breast",
  C53: "Malignant neoplasm of cervix uteri",
  C54: "Malignant neoplasm of corpus uteri",
  C61: "Malignant neoplasm of prostate",
  C64: "Malignant neoplasm of kidney, except renal pelvis",
  C67: "Malignant neoplasm of bladder",
  C77: "Secondary and unspecified malignant neoplasm of lymph nodes",
  C78: "Secondary malignant neoplasm of respiratory and digestive organs",
  C79: "Secondary malignant neoplasm of other and unspecified sites",
  C80: "Malignant neoplasm, without specification of site",
  D00: "Carcinoma in situ of oral cavity, oesophagus and stomach",
  D01: "Carcinoma in situ of other and unspecified digestive organs",
  D02: "Carcinoma in situ of middle ear and respiratory system",
  D05: "Carcinoma in situ of breast",
  D09: "Carcinoma in situ of other and unspecified sites",
  D10: "Benign neoplasm of mouth and pharynx",
  D11: "Benign neoplasm of major salivary glands",
  D12: "Benign neoplasm of colon, rectum, anus and anal canal",
  D13: "Benign neoplasm of other and ill-defined parts of digestive system",
  D14: "Benign neoplasm of middle ear and respiratory system",
  D15: "Benign neoplasm of other and unspecified intrathoracic organs",
  D16: "Benign neoplasm of bone and articular cartilage",
  D17: "Benign lipomatous neoplasm",
  D18: "Haemangioma and lymphangioma, any site",
  D20: "Benign neoplasm of soft tissue of retroperitoneum and peritoneum",
  D21: "Other benign neoplasms of connective and other soft tissue",
  D25: "Leiomyoma of uterus",
  D37: "Neoplasm of uncertain or unknown behaviour of oral cavity and digestive organs",
  D38: "Neoplasm of uncertain or unknown behaviour of middle ear and respiratory and intrathoracic organs",
  D39: "Neoplasm of uncertain or unknown behaviour of female genital organs",
  D40: "Neoplasm of uncertain or unknown behaviour of male genital organs",
  D41: "Neoplasm of uncertain or unknown behaviour of urinary organs",
  D43: "Neoplasm of uncertain or unknown behaviour of brain and central nervous system",
  D44: "Neoplasm of uncertain or unknown behaviour of endocrine glands",
  D45: "Polycythaemia vera",
  D46: "Myelodysplastic syndromes",
  D47: "Other neoplasms of uncertain or unknown behaviour of lymphoid, haematopoietic and related tissue",
  D48: "Neoplasm of uncertain or unknown behaviour of other and unspecified sites",
  D50: "Iron deficiency anaemia",
  D51: "Vitamin B 12 deficiency anaemia",
  D52: "Folate deficiency anaemia",
  D53: "Other nutritional anaemias",
  D55: "Anaemia due to enzyme disorders",
  D56: "Thalassaemia",
  D57: "Sickle-cell disorders",
  D58: "Other hereditary haemolytic anaemias",
  D59: "Acquired haemolytic anaemia",
  D60: "Acquired pure red cell aplasia [erythroblastopenia]",
  D61: "Other aplastic anaemias",
  D62: "Acute posthaemorrhagic anaemia",
  D63: "Anaemia in chronic diseases classified elsewhere",
  D64: "Other anaemias",
  D65: "Disseminated intravascular coagulation [defibrination syndrome]",
  D66: "Hereditary factor VIII deficiency",
  D67: "Hereditary factor IX deficiency",
  D68: "Other coagulation defects",
  D69: "Purpura and other haemorrhagic conditions",
  D70: "Agranulocytosis",
  D71: "Functional disorders of polymorphonuclear neutrophils",
  D72: "Other disorders of white blood cells",
  D73: "Diseases of spleen",
  D74: "Methaemoglobinaemia",
  D75: "Other diseases of blood and blood-forming organs",
  D76: "Other specified diseases with participation of lymphoreticular and reticulohistiocytic tissue",
  D77: "Other disorders of blood and blood-forming organs in diseases classified elsewhere",
  D80: "Immunodeficiency with predominantly antibody defects",
  D81: "Combined immunodeficiencies",
  D82: "Immunodeficiency associated with other major defects",
  D83: "Common variable immunodeficiency",
  D84: "Other immunodeficiencies",
  D86: "Sarcoidosis",
  D89: "Other disorders involving the immune mechanism, not elsewhere classified",
  E05: "Thyrotoxicosis [hyperthyroidism]",
  E06: "Thyroiditis",
  E07: "Other disorders of thyroid",
  E10: "Type 1 diabetes mellitus",
  E11: "Type 2 diabetes mellitus",
  E13: "Other specified diabetes mellitus",
  E14: "Unspecified diabetes mellitus",
  E44: "Protein-energy malnutrition of moderate and mild degree",
  E46: "Unspecified protein-energy malnutrition",
  E83: "Disorders of mineral metabolism",
  E84: "Cystic fibrosis",
  E85: "Amyloidosis",
  E86: "Volume depletion",
  E87: "Other disorders of fluid, electrolyte and acid-base balance",
  F10: "Mental and behavioural disorders due to use of alcohol",
  F17: "Mental and behavioural disorders due to use of tobacco",
  F32: "Depressive episode",
  F33: "Recurrent depressive disorder",
  F40: "Phobic anxiety disorders",
  F41: "Other anxiety disorders",
  F45: "Somatoform disorders",
  F50: "Eating disorders",
  G40: "Epilepsy",
  G43: "Migraine",
  I10: "Essential (primary) hypertension",
  I20: "Angina pectoris",
  I21: "Acute myocardial infarction",
  I25: "Chronic ischaemic heart disease",
  I35: "Nonrheumatic aortic valve disorders",
  I42: "Cardiomyopathy",
  I48: "Atrial fibrillation and flutter",
  I50: "Heart failure",
  I63: "Cerebral infarction",
  I82: "Other venous embolism and thrombosis",
  I83: "Varicose veins of lower extremities",
  I84: "Haemorrhoids",
  I85: "Oesophageal varices",
  I86: "Varicose veins of other sites",
  J06: "Acute upper respiratory infections of multiple and unspecified sites",
  J18: "Pneumonia, organism unspecified",
  J44: "Other chronic obstructive pulmonary disease",
  J98: "Other respiratory disorders",
  K00: "Disorders of tooth development and eruption",
  K01: "Embedded and impacted teeth",
  K02: "Dental caries",
  K03: "Other diseases of hard tissues of teeth",
  K04: "Diseases of pulp and periapical tissues",
  K05: "Gingivitis and periodontal diseases",
  K06: "Other disorders of gingiva and edentulous alveolar ridge",
  K07: "Dentofacial anomalies [including malocclusion]",
  K08: "Other disorders of teeth and supporting structures",
  K09: "Cysts of oral region, not elsewhere classified",
  K10: "Other diseases of jaws",
  K11: "Diseases of salivary glands",
  K12: "Stomatitis and related lesions",
  K13: "Other diseases of lip and oral mucosa",
  K14: "Diseases of tongue",
  K20: "Oesophagitis",
  K21: "Gastro-oesophageal reflux disease",
  K22: "Other diseases of oesophagus",
  K23: "Disorders of oesophagus in diseases classified elsewhere",
  K25: "Gastric ulcer",
  K26: "Duodenal ulcer",
  K27: "Peptic ulcer, site unspecified",
  K28: "Gastrojejunal ulcer",
  K29: "Gastritis and duodenitis",
  K30: "Functional dyspepsia",
  K31: "Other diseases of stomach and duodenum",
  K35: "Acute appendicitis",
  K36: "Other appendicitis",
  K37: "Unspecified appendicitis",
  K38: "Other diseases of appendix",
  K40: "Inguinal hernia",
  K41: "Femoral hernia",
  K42: "Umbilical hernia",
  K43: "Ventral hernia",
  K44: "Diaphragmatic hernia",
  K45: "Other abdominal hernia",
  K46: "Unspecified abdominal hernia",
  K50: "Crohn disease [regional enteritis]",
  K51: "Ulcerative colitis",
  K52: "Other noninfective gastroenteritis and colitis",
  K55: "Vascular disorders of intestine",
  K56: "Paralytic ileus and intestinal obstruction without hernia",
  K57: "Diverticular disease of intestine",
  K58: "Irritable bowel syndrome",
  K59: "Other functional intestinal disorders",
  K60: "Fissure and fistula of anal and rectal regions",
  K61: "Abscess of anal and rectal regions",
  K62: "Other diseases of anus and rectum",
  K63: "Other diseases of intestine",
  K64: "Haemorrhoids and perianal venous thrombosis",
  K65: "Peritonitis",
  K66: "Other disorders of peritoneum",
  K67: "Disorders of peritoneum in infectious diseases classified elsewhere",
  K70: "Alcoholic liver disease",
  K71: "Toxic liver disease",
  K72: "Hepatic failure, not elsewhere classified",
  K73: "Chronic hepatitis, not elsewhere classified",
  K74: "Fibrosis and cirrhosis of liver",
  K75: "Other inflammatory liver diseases",
  K76: "Other diseases of liver",
  K77: "Liver disorders in diseases classified elsewhere",
  K80: "Cholelithiasis",
  K81: "Cholecystitis",
  K82: "Other diseases of gallbladder",
  K83: "Other diseases of biliary tract",
  K85: "Acute pancreatitis",
  K86: "Other diseases of pancreas",
  K87: "Disorders of gallbladder, biliary tract and pancreas in diseases classified elsewhere",
  K90: "Intestinal malabsorption",
  K91: "Postprocedural disorders of digestive system, not elsewhere classified",
  K92: "Other diseases of digestive system",
  K93: "Disorders of other digestive organs in diseases classified elsewhere",
  L40: "Psoriasis",
  M05: "Seropositive rheumatoid arthritis",
  M06: "Other rheumatoid arthritis",
  M10: "Gout",
  M32: "Systemic lupus erythematosus",
  N18: "Chronic kidney disease",
  N19: "Unspecified kidney failure",
  N39: "Other disorders of urinary system",
  N40: "Hyperplasia of prostate",
  O21: "Excessive vomiting in pregnancy",
  Q38: "Other congenital malformations of tongue, mouth and pharynx",
  Q39: "Congenital malformations of oesophagus",
  Q40: "Other congenital malformations of upper alimentary tract",
  Q41: "Congenital absence, atresia and stenosis of small intestine",
  Q42: "Congenital absence, atresia and stenosis of large intestine",
  Q43: "Other congenital malformations of intestine",
  Q44: "Congenital malformations of gallbladder, bile ducts and liver",
  Q45: "Other congenital malformations of digestive system",
  R00: "Abnormalities of heart beat",
  R04: "Haemorrhage from respiratory passages",
  R10: "Abdominal and pelvic pain",
  R11: "Nausea and vomiting",
  R12: "Heartburn",
  R13: "Dysphagia",
  R14: "Flatulence and related conditions",
  R15: "Faecal incontinence",
  R16: "Hepatomegaly and splenomegaly, not elsewhere classified",
  R17: "Hyperbilirubinaemia, with or without jaundice, not elsewhere classified",
  R18: "Ascites",
  R19: "Other symptoms and signs involving the digestive system and abdomen",
  R50: "Fever of other and unknown origin",
  R57: "Shock, not elsewhere classified",
  R63: "Symptoms and signs concerning food and fluid intake",
  R73: "Elevated blood glucose level",
  R74: "Abnormal serum enzyme levels",
  R79: "Other abnormal findings of blood chemistry",
  S36: "Injury of intra-abdominal organs",
  T39: "Poisoning by nonopioid analgesics, antipyretics and antirheumatics",
  T71: "Asphyxiation",
  Z03: "Medical observation and evaluation for suspected diseases and conditions, ruled out",
  Z04: "Examination and observation for other reasons",
  Z08: "Follow-up examination after treatment for malignant neoplasms",
  Z09: "Follow-up examination after treatment for conditions other than malignant neoplasms",
  Z10: "Routine general health check-up of defined subpopulation",
  Z11: "Special screening examination for infectious and parasitic diseases",
  Z12: "Special screening examination for neoplasms",
  Z13: "Special screening examination for other diseases and disorders",
  Z18: "Retained foreign body fragments",
  Z41: "Procedures for purposes other than remedying health state",
  Z43: "Attention to artificial openings",
  Z45: "Adjustment and management of implanted device",
  Z46: "Fitting and adjustment of other devices",
  Z48: "Other surgical follow-up care",
  Z51: "Other medical care",
  Z54: "Convalescence",
  Z71: "Persons encountering health services for other counselling and medical advice, not elsewhere classified",
  Z72: "Problems related to lifestyle",
  Z76: "Persons encountering health services in other circumstances",
  Z80: "Family history of malignant neoplasm",
  Z83: "Family history of other specific disorders",
  Z85: "Personal history of malignant neoplasm",
  Z86: "Personal history of certain other diseases",
  Z87: "Personal history of other diseases and conditions",
  Z92: "Personal history of medical treatment",
  Z95: "Presence of cardiac and vascular implants and grafts",
  Z96: "Presence of other functional implants",
  Z98: "Other postsurgical states",
};

export default MKN10_EN;
