/**
 * Czech MKN-10 (ICD-10) diagnosis code → name lookup.
 * 3-character codes, sourced from ÚZIS ČR – mkn10.uzis.cz
 * Covers: K (full GI chapter), C00-C80, D00-D89 (full),
 *         Q38-Q45, A00-A09, B15-B19, R10-R19, E, F, I, Z + common comorbidity codes.
 */
const MKN10_CS = {
  // ── A – Infekční a parazitární nemoci ─────────────────────────────────
  A00: "Cholera",
  A01: "Tyfus a paratyfus",
  A02: "Jiné salmonelové infekce",
  A03: "Šigelóza",
  A04: "Jiné bakteriální střevní infekce",
  A05: "Jiné bakteriální alimentární otravy",
  A06: "Amébóza",
  A07: "Jiné protozoální střevní nemoci",
  A08: "Virové a jiné určené střevní infekce",
  A09: "Průjem a gastroenteritida pravděp. infekčního původu",
  A15: "Respirační tuberkulóza, bakteriologicky potvrzená",
  A16: "Respirační tuberkulóza, bakteriologicky nepotvrzená",
  A17: "Tuberkulóza nervového systému",
  A18: "Tuberkulóza jiných orgánů",
  A19: "Miliární tuberkulóza",
  A40: "Streptokoková sepse",
  A41: "Jiná sepse",
  A49: "Bakteriální infekce, neurčená",

  // ── B – Virové hepatitidy ──────────────────────────────────────────────
  B15: "Akutní hepatitida A",
  B16: "Akutní hepatitida B",
  B17: "Jiné akutní virové hepatitidy",
  B18: "Chronická virová hepatitida",
  B19: "Virová hepatitida NS",
  B20: "Nemoc vyvolaná HIV s infekcemi",
  B94: "Následky jiných a neurčených infekčních nemocí",

  // ── C – Zhoubné novotvary ────────────────────────────────────────────
  C00: "Zhoubný novotvar rtu",
  C01: "Zhoubný novotvar kořene jazyka",
  C02: "Zhoubný novotvar jiných částí jazyka",
  C03: "Zhoubný novotvar dásní",
  C04: "Zhoubný novotvar dna dutiny ústní",
  C05: "Zhoubný novotvar patra",
  C06: "Zhoubný novotvar jiných částí dutiny ústní",
  C07: "Zhoubný novotvar příušní žlázy",
  C08: "Zhoubný novotvar jiných slinných žláz",
  C09: "Zhoubný novotvar mandle",
  C10: "Zhoubný novotvar ústní části hltanu",
  C11: "Zhoubný novotvar nosní části hltanu",
  C12: "Zhoubný novotvar piriformního sinu",
  C13: "Zhoubný novotvar dolní části hltanu",
  C14: "Zhoubný novotvar rtu, dutiny ústní a hltanu",
  C15: "Zhoubný novotvar jícnu",
  C16: "Zhoubný novotvar žaludku",
  C17: "Zhoubný novotvar tenkého střeva",
  C18: "Zhoubný novotvar tlustého střeva",
  C19: "Zhoubný novotvar rektosigmoidálního spojení",
  C20: "Zhoubný novotvar konečníku",
  C21: "Zhoubný novotvar řitního kanálu a řiti",
  C22: "Zhoubný novotvar jater a intrahepatálních žlučových cest",
  C23: "Zhoubný novotvar žlučníku",
  C24: "Zhoubný novotvar jiných částí žlučových cest",
  C25: "Zhoubný novotvar slinivky břišní",
  C26: "Zhoubný novotvar jiných orgánů trávicí soustavy",
  C34: "Zhoubný novotvar průdušky a plíce",
  C50: "Zhoubný novotvar prsu",
  C53: "Zhoubný novotvar hrdla děložního",
  C54: "Zhoubný novotvar těla děložního",
  C61: "Zhoubný novotvar prostaty",
  C64: "Zhoubný novotvar ledviny",
  C67: "Zhoubný novotvar močového měchýře",
  C77: "Sekundární a neurčený ZN lymfatických uzlin",
  C78: "Sekundární ZN dýchacích a trávicích orgánů",
  C79: "Sekundární ZN jiných orgánů",
  C80: "Zhoubný novotvar bez určení místa",

  // ── D00–D48 – Novotvary ───────────────────────────────────────────────
  D00: "Karcinom in situ dutiny ústní, jícnu a žaludku",
  D01: "Karcinom in situ jiných orgánů trávicí soustavy",
  D02: "Karcinom in situ středního ucha a dýchacích orgánů",
  D05: "Karcinom in situ prsu",
  D09: "Karcinom in situ jiných orgánů",
  D10: "Nezhoubný novotvar dutiny ústní a hltanu",
  D11: "Nezhoubný novotvar slinných žláz",
  D12: "Nezhoubný novotvar tlustého střeva, konečníku a řiti",
  D13: "Nezhoubný novotvar jiných orgánů trávicí soustavy",
  D14: "Nezhoubný novotvar středního ucha a dýchacích orgánů",
  D15: "Nezhoubný novotvar jiných a neurčených nitrohrudních orgánů",
  D16: "Nezhoubný novotvar kostí a kloubní chrupavky",
  D17: "Lipom",
  D18: "Hemangiom a lymfangiom",
  D20: "Nezhoubný novotvar pobřišnice a retroperitonea",
  D21: "Jiné nezhoubné novotvary pojivové a jiné měkké tkáně",
  D25: "Leiomyom dělohy",
  D37: "Novotvar nejistého chování trávicí soustavy a peritonea",
  D38: "Novotvar nejistého chování středního ucha a dýchacích orgánů",
  D39: "Novotvar nejistého chování ženských pohlavních orgánů",
  D40: "Novotvar nejistého chování mužských pohlavních orgánů",
  D41: "Novotvar nejistého chování močových orgánů",
  D43: "Novotvar nejistého chování mozku a centrální nervové soustavy",
  D44: "Novotvar nejistého chování endokrinních žláz",
  D45: "Polycytémia vera",
  D46: "Myelodysplastické syndromy",
  D47: "Jiné novotvary nejistého chování lymfatické a krvetvorné tkáně",
  D48: "Novotvar nejistého chování jiných a neurčených lokalizací",

  // ── D50–D89 – Nemoci krve, krvetvorných orgánů a poruchy imunity ──────
  D50: "Sideropenická anémie",
  D51: "Anémie z nedostatku vitamínu B12",
  D52: "Anémie z nedostatku kyseliny listové",
  D53: "Jiné nutriční anémie",
  D55: "Anémie při enzymových poruchách",
  D56: "Talasémie",
  D57: "Srpkovité poruchy",
  D58: "Jiné dědičné hemolytické anémie",
  D59: "Získaná hemolytická anémie",
  D60: "Získaná čistá aplazie červené řady",
  D61: "Jiné aplastické anémie",
  D62: "Akutní posthemorragická anémie",
  D63: "Anémie při chronických nemocech zař. jinde",
  D64: "Jiné anémie",
  D65: "Disseminovaná intravaskulární koagulace",
  D66: "Dědičný deficit faktoru VIII",
  D67: "Dědičný deficit faktoru IX",
  D68: "Jiné koagulopatie",
  D69: "Purpura a jiné hemoragické stavy",
  D70: "Agranulocytóza",
  D71: "Funkční poruchy polymorfonukleárních neutrofilů",
  D72: "Jiné poruchy bílých krvinek",
  D73: "Nemoci sleziny",
  D74: "Methemoglobinemie",
  D75: "Jiné nemoci krve a krvetvorných orgánů",
  D76: "Histiocytární choroby a retikulohistiocytózy",
  D77: "Jiné poruchy krve a krvetvorných orgánů jinde zař.",
  D80: "Imunodeficience s převahou nedostatku protilátek",
  D81: "Kombinované imunodeficience",
  D82: "Imunodeficience sdružené s jinými závažnými vadami",
  D83: "Běžná variabilní imunodeficience",
  D84: "Jiné imunodeficience",
  D86: "Sarkoidóza",
  D89: "Jiné poruchy imunního mechanismu jinde nezař.",

  // ── E – Endokrinní, výživové a metabolické nemoci ─────────────────────
  E05: "Thyreotoxikóza",
  E06: "Thyroiditida",
  E07: "Jiné nemoci štítné žlázy",
  E10: "Diabetes mellitus 1. typu",
  E11: "Diabetes mellitus 2. typu",
  E13: "Jiné určené formy diabetes mellitus",
  E14: "Diabetes mellitus NS",
  E44: "Podvýživa střední a mírné závažnosti",
  E46: "Podvýživa NS",
  E83: "Poruchy metabolismu minerálů",
  E84: "Cystická fibróza",
  E85: "Amyloidóza",
  E86: "Hypovolémie",
  E87: "Jiné poruchy rovnováhy tekutin, elektrolytů a acidobaze",

  // ── F – Duševní poruchy ──────────────────────────────────────────────
  F10: "Poruchy způsobené alkoholem",
  F17: "Poruchy způsobené tabákem",
  F32: "Depresivní fáze",
  F33: "Periodická depresivní porucha",
  F40: "Fobické úzkostné poruchy",
  F41: "Jiné úzkostné poruchy",
  F45: "Somatoformní poruchy",
  F50: "Poruchy příjmu potravy",

  // ── G – Nemoci nervového systému ─────────────────────────────────────
  G40: "Epilepsie",
  G43: "Migréna",

  // ── I – Nemoci oběhové soustavy ──────────────────────────────────────
  I10: "Esenciální (primární) hypertenze",
  I20: "Nestabilní angina pectoris a jiné formy ICHS",
  I21: "Akutní infarkt myokardu",
  I25: "Chronická ischemická nemoc srdeční",
  I35: "Nerevmatická onemocnění aortální chlopně",
  I42: "Kardiomyopatie",
  I48: "Fibrilace a flutter síní",
  I50: "Srdeční selhání",
  I63: "Infarkt mozku",
  I82: "Embolie a trombóza jiných žil",
  I83: "Křečové žíly dolních končetin",
  I84: "Hemoroidy",
  I85: "Jícnové varixy",
  I86: "Křečové žíly jiných lokalizací",

  // ── J – Nemoci dýchací soustavy ──────────────────────────────────────
  J06: "Akutní infekce horních cest dýchacích",
  J18: "Pneumonie NS",
  J44: "Jiné chronické obstrukční nemoci plic",
  J98: "Jiné nemoci dýchacích cest",

  // ── K – Nemoci trávicí soustavy (kompletní) ──────────────────────────
  K00: "Poruchy vývoje a prořezávání zubů",
  K01: "Impaktované zuby",
  K02: "Zubní kaz",
  K03: "Jiné nemoci tvrdých zubních tkání",
  K04: "Nemoci zubní dřeně a periapikálních tkání",
  K05: "Gingivitida a parodontální nemoci",
  K06: "Jiné nemoci dásní a bezzubých alveolárních výběžků",
  K07: "Dentofaciální anomálie včetně nesprávného skusu",
  K08: "Jiné nemoci zubů a jejich podpůrných struktur",
  K09: "Cysty ústní oblasti",
  K10: "Jiné nemoci čelistí",
  K11: "Nemoci slinných žláz",
  K12: "Stomatitida a příbuzné léze",
  K13: "Jiné nemoci rtu a sliznice dutiny ústní",
  K14: "Nemoci jazyka",
  K20: "Ezofagitida",
  K21: "Gastroezofageální refluxní nemoc",
  K22: "Jiné nemoci jícnu",
  K23: "Poruchy jícnu při nemocech zařazených jinde",
  K25: "Vřed žaludku",
  K26: "Vřed dvanáctníku",
  K27: "Peptický vřed NS",
  K28: "Gastrojejunální vřed",
  K29: "Gastritida a duodenitida",
  K30: "Funkční dyspepsie",
  K31: "Jiné nemoci žaludku a dvanáctníku",
  K35: "Akutní apendicitida",
  K36: "Jiné apendicitidy",
  K37: "Apendicitida NS",
  K38: "Jiné nemoci appendixu",
  K40: "Tříselná kýla",
  K41: "Stehenní kýla",
  K42: "Pupečníková kýla",
  K43: "Kýla přední stěny břišní",
  K44: "Brániční kýla",
  K45: "Jiné kýly břicha",
  K46: "Neurčená kýla břicha",
  K50: "Crohnova nemoc",
  K51: "Ulcerózní kolitida",
  K52: "Jiné neinfekční gastroenteritidy a kolitidy",
  K55: "Vaskulární nemoci střev",
  K56: "Paralytický ileus a neprůchodnost střeva bez kýly",
  K57: "Divertikulární nemoc střeva",
  K58: "Syndrom dráždivého střeva (IBS)",
  K59: "Jiné funkční střevní poruchy",
  K60: "Fisury a píštěle análního a rektálního regionu",
  K61: "Absces análního a rektálního regionu",
  K62: "Jiné nemoci konečníku a řitního kanálu",
  K63: "Jiné nemoci střev",
  K64: "Hemoroidy a anální venózní trombóza",
  K65: "Peritonitida",
  K66: "Jiné afekce pobřišnice",
  K67: "Poruchy pobřišnice při infekčních nemocech",
  K70: "Alkoholická jaterní nemoc",
  K71: "Toxická jaterní nemoc",
  K72: "Jaterní selhání",
  K73: "Chronická hepatitida",
  K74: "Fibróza a cirhóza jater",
  K75: "Jiné zánětlivé jaterní nemoci",
  K76: "Jiné nemoci jater",
  K77: "Jaterní poruchy při nemocech zařazených jinde",
  K80: "Cholelitiáza",
  K81: "Cholecystitida",
  K82: "Jiné nemoci žlučníku",
  K83: "Jiné nemoci žlučových cest",
  K85: "Akutní pankreatitida",
  K86: "Jiné nemoci slinivky břišní",
  K87: "Poruchy žlučníku, žlučových cest a slinivky jinde zař.",
  K90: "Střevní malabsorpce",
  K91: "Poruchy trávicího ústrojí po lékařských výkonech",
  K92: "Jiné nemoci trávicí soustavy",
  K93: "Poruchy jiných orgánů trávicí soustavy jinde zař.",

  // ── L – Kůže ─────────────────────────────────────────────────────────
  L40: "Psoriáza",

  // ── M – Muskuloskeletální ────────────────────────────────────────────
  M05: "Séropozitivní revmatoidní artritida",
  M06: "Jiná revmatoidní artritida",
  M10: "Dna",
  M32: "Systémový lupus erythematosus",

  // ── N – Urogenitální ─────────────────────────────────────────────────
  N18: "Chronické onemocnění ledvin",
  N19: "Selhání ledvin NS",
  N39: "Jiné nemoci močového ústrojí",
  N40: "Hyperplazie prostaty",

  // ── O – Těhotenství a porod ──────────────────────────────────────────
  O21: "Nadměrné zvracení v těhotenství",

  // ── Q – Vrozené vady trávicí soustavy ────────────────────────────────
  Q38: "Jiné vrozené vady jazyka, dutiny ústní a hltanu",
  Q39: "Vrozené vady jícnu",
  Q40: "Jiné vrozené vady horní části trávicí soustavy",
  Q41: "Vrozená atrézie a stenóza tenkého střeva",
  Q42: "Vrozená atrézie a stenóza tlustého střeva",
  Q43: "Jiné vrozené vady střeva",
  Q44: "Vrozené vady žlučníku, žlučových cest a jater",
  Q45: "Jiné vrozené vady trávicí soustavy",

  // ── R – Příznaky a znaky (GIT a břicho) ──────────────────────────────
  R00: "Abnormality srdeční frekvence",
  R04: "Krvácení z dýchacích cest",
  R10: "Bolest břicha a pánevní oblasti",
  R11: "Nauzea a zvracení",
  R12: "Pálení žáhy",
  R13: "Afagie a dysfagie",
  R14: "Plynatost a příbuzné stavy",
  R15: "Inkontinence stolice",
  R16: "Hepatomegalie a splenomegalie",
  R17: "Žloutenka NS",
  R18: "Ascites",
  R19: "Jiné příznaky a znaky trávicí soustavy a břicha",
  R50: "Horečka NS",
  R57: "Šok NS",
  R63: "Příznaky týkající se příjmu potravy a tekutin",
  R73: "Zvýšená glukóza v krvi",
  R74: "Abnormální hladiny enzymů v séru",
  R79: "Jiné abnormální nálezy v chemii krve",

  // ── S – Úrazy ────────────────────────────────────────────────────────
  S36: "Úraz nitrobřišního orgánu",

  // ── T – Otravy ───────────────────────────────────────────────────────
  T39: "Otrava neopioidními analgetiky",
  T71: "Asfyxie",

  // ── Z – Faktory ovlivňující zdravotní stav ───────────────────────────
  Z03: "Lékařské pozorování a hodnocení",
  Z04: "Vyšetření a pozorování z jiných důvodů",
  Z08: "Následné vyšetření po léčbě zhoubného novotvaru",
  Z09: "Sledování po léčbě jiných nemocí",
  Z10: "Rutinní celkové vyšetření zdravotního stavu",
  Z11: "Screeningové vyšetření na infekční nemoci",
  Z12: "Screeningové vyšetření na novotvary",
  Z13: "Screeningové vyšetření na jiné nemoci a poruchy",
  Z18: "Zbytky cizích těles",
  Z41: "Výkony pro jiné účely než léčbu",
  Z43: "Péče o umělé otvory",
  Z45: "Seřízení a ošetření implantovaného zařízení",
  Z46: "Nasazení a úprava jiných zařízení",
  Z48: "Jiná pooperační péče",
  Z51: "Jiné lékařské péče",
  Z54: "Stav rekonvalescence",
  Z71: "Osoby hledající poradenství",
  Z72: "Problémy spojené se způsobem života",
  Z76: "Osoby přicházející do styku se zdravotní péčí z jiných důvodů",
  Z80: "Rodinná anamnéza zhoubných novotvarů",
  Z83: "Rodinná anamnéza chorob trávicí soustavy",
  Z85: "Osobní anamnéza zhoubných novotvarů",
  Z86: "Osobní anamnéza určitých dalších nemocí",
  Z87: "Osobní anamnéza jiných nemocí",
  Z92: "Osobní anamnéza lékařské léčby",
  Z95: "Přítomnost srdečních a cévních implantátů a štěpů",
  Z96: "Přítomnost jiných funkčních implantátů",
  Z98: "Jiné stav po chirurgickém výkonu",
};

export default MKN10_CS;

/**
 * Returns "CODE / Název diagnózy" or just "CODE" if not found.
 */
export function mkn10Label(code) {
  if (!code) return "";
  const name = MKN10_CS[code];
  return name ? `${code} / ${name}` : code;
}

/**
 * Returns just the Czech name, or the code as fallback.
 */
export function mkn10Name(code) {
  if (!code) return "";
  return MKN10_CS[code] ?? code;
}
